### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by andrenventer** [oneto018/vertx-3-clojure#1]
lein run
Reflection warning, /private/var/folders/62/rp5pcvyx70vcgmg0yxvjlgc40000gn/T/form-init8208287222138716318.clj:1:949 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).
Reflection warning, vertx/route.clj:36:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:36:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:37:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:37:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:38:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:38:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:39:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:39:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:40:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:40:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:41:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:41:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:42:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:42:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:43:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:43:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:44:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:44:1 - call to method handler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:46:1 - call to method route can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:46:1 - call to method blockingHandler can't be resolved (target class is unknown).
Reflection warning, vertx/route.clj:46:1 - call to method route can't be resolved (target class is unknown).
Exception in thread "main" java.lang.RuntimeException: No such var: vertx.route/orderered, compiling:(vertx/route.clj:46:1)
    at clojure.lang.Compiler.analyze(Compiler.java:6543)
    at clojure.lang.Compiler.analyze(Compiler.java:6485)
    at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:996)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyze(Compiler.java:6485)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.access$300(Compiler.java:38)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyze(Compiler.java:6485)
    at clojure.lang.Compiler.eval(Compiler.java:6786)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at vertx_web_clj.core$eval22$loading__5340__auto____23.invoke(core.clj:1)
    at vertx_web_clj.core$eval22.invoke(core.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6771)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval7$fn__9.invoke(form-init8208287222138716318.clj:1)
    at user$eval7.invoke(form-init8208287222138716318.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6772)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: vertx.route/orderered
    at clojure.lang.Util.runtimeException(Util.java:221)
    at clojure.lang.Compiler.resolveIn(Compiler.java:6993)
    at clojure.lang.Compiler.resolve(Compiler.java:6963)
    at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6924)
    at clojure.lang.Compiler.analyze(Compiler.java:6506)
    ... 78 more

**Comment by oneto018** [comment]
I messed up the macros in routes . For now I removed the macro usage and manually copy pasted functions for http methods. Now this is fixed. Can you verify this

**Comment by andrenventer** [comment]
Fixed!

I get:

http://localhost:8083/ => home page
http://localhost:8083/t1 => t1 content
http://localhost:8083/hello/somename => hello somename!

console:

lein run
Reflection warning, /private/var/folders/62/rp5pcvyx70vcgmg0yxvjlgc40000gn/T/form-init5947096617595948757.clj:1:949 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).
server started and running at port 8083 #object[io.vertx.core.impl.FutureImpl 0x690a6b03 io.vertx.core.impl.FutureImpl@690a6b03]

**Comment by oneto018** [comment]
ok. thank you.

**Comment by andrenventer** [comment]
Clojure and micro services are a great match - your efforts with Vert.x are very valuable :)

**Comment by oneto018** [comment]
Actually , for vertx2 there is full support for clojure. Unfortunately for
vertx 3 not yet. I wanted to try directly using Java apis.
